#!/bin/bash
#   Copyright (C) 2012-2020 University of Oxford
#
#   SHCOPYRIGHT
if [ $# -le 3 ] ; then
  echo "$0 <randomise options>"
  echo ""
  echo "Actual number of permutations performed may differ slightly from those
  requested due to tasking an equal number of permutations per fragment."
  echo ""
  echo "Caution: if a design has less unique permutations than those requested,
  the defragment script will not work correctly!"
  exit 1
fi

if ! RANDOMISE_OUTPUT=$($FSLDIR/bin/randomise "$@" -Q) ; then
  echo "ERROR: Randomise could not succesfully initialise with the command line given. Submission aborted."
  exit 1
fi

PERMS=$(echo "$RANDOMISE_OUTPUT" | awk '{print $1}')
CONTRASTS=$(echo "$RANDOMISE_OUTPUT" | awk '{print $2}')
ROOTNAME=$(echo "$RANDOMISE_OUTPUT" | awk '{print $3}')
BASENAME=$(basename $ROOTNAME)
DIRNAME=$(dirname $ROOTNAME)

mkdir -p ${DIRNAME}/${BASENAME}_logs

PERMS_PER_SLOT=$(echo $RANDOMISE_OUTPUT | awk '{print $4}')
if [ -z "${REQUESTED_TIME}" ] ; then
    REQUESTED_TIME=30
fi

SLOTS_PER_CONTRAST=$((PERMS / PERMS_PER_SLOT))

if [[ $SLOTS_PER_CONTRAST -lt 1 ]] ; then
    SLOTS_PER_CONTRAST=1
fi

PERMS_PER_CONTRAST=$((PERMS_PER_SLOT * SLOTS_PER_CONTRAST))

REQUESTED_SLOTS=$((CONTRASTS * SLOTS_PER_CONTRAST))

CORRECTED_PERMS=$((PERMS_PER_CONTRAST - SLOTS_PER_CONTRAST))
CORRECTED_PERMS=$((CORRECTED_PERMS + 1))

echo "Generating $REQUESTED_SLOTS fragments for $CONTRASTS contrasts with $PERMS_PER_SLOT permutations per fragment. Allocating ${REQUESTED_TIME} minutes per fragment."
echo "The total number of permutations per contrast will be $PERMS_PER_CONTRAST."

#stage 1:
CURRENT_SEED=1
if [[ -e "${DIRNAME}/${BASENAME}.generate" ]] ; then
  /bin/rm "${DIRNAME}/${BASENAME}.generate"
fi
while [[ $CURRENT_SEED -le $SLOTS_PER_CONTRAST ]] ; do
  SLEEPTIME=$((1 * CURRENT_SEED)) # Why is this necessary?
  CURRENT_CONTRAST=1
  while [[ $CURRENT_CONTRAST -le "$CONTRASTS" ]] ; do
      if [[ "${CONTRASTS}" -ne 1 ]]; then
	  SKIPTO=" --skipTo=$CURRENT_CONTRAST "
      fi
      echo "FSLOUTPUTTYPE=NIFTI_GZ; sleep $SLEEPTIME ; ${FSLDIR}/bin/randomise $* -n $PERMS_PER_SLOT -o ${ROOTNAME}_SEED${CURRENT_SEED} --seed=$CURRENT_SEED ${SKIPTO}" >> ${DIRNAME}/${BASENAME}.generate
      CURRENT_CONTRAST=$((CURRENT_CONTRAST + 1))
  done
  echo "done $CURRENT_SEED"
  CURRENT_SEED=$((CURRENT_SEED + 1))
done
chmod a+x "${DIRNAME}/${BASENAME}.generate"
GENERATE_ID=$("$FSLDIR/bin/fsl_sub" -T ${REQUESTED_TIME} -N "${BASENAME}.generate" -n -l "${DIRNAME}/${BASENAME}_logs/" -t "${DIRNAME}/${BASENAME}.generate")

#stage2:
(
  cat <<combineScript
#!/bin/bash
echo "Merging stat images"
for FIRSTSEED in \$(imglob -extension "${ROOTNAME}_SEED1_"*_p_* "${ROOTNAME}_SEED1_"*_corrp_*) ; do
  ADDCOMMAND=""
  ACTIVESEED=1
  if [ -e \$FIRSTSEED ] ; then
    while [ \$ACTIVESEED -le $SLOTS_PER_CONTRAST ] ; do
      ADDCOMMAND=\$(echo \$ADDCOMMAND -add \${FIRSTSEED/_SEED1_/_SEED\${ACTIVESEED}_})
      ACTIVESEED=\$((ACTIVESEED + 1))
    done
    ADDCOMMAND=\${ADDCOMMAND#-add}
    echo \$ADDCOMMAND
    \$FSLDIR/bin/fslmaths \$ADDCOMMAND -mul $PERMS_PER_SLOT -div $CORRECTED_PERMS \${FIRSTSEED/_SEED1/}
  fi
done

echo "Merging text files"
for FIRSTSEED in "${ROOTNAME}_SEED1_"*perm_*.txt "${ROOTNAME}_SEED1_"*_p_*.txt "${ROOTNAME}_SEED1_"*_corrp_*.txt ; do
  ACTIVESEED=1
  if [ -e \$FIRSTSEED ] ; then
    while [ \$ACTIVESEED -le $SLOTS_PER_CONTRAST ] ; do
      if [ \$ACTIVESEED -eq 1 ] ; then
         cat \${FIRSTSEED/_SEED1_/_SEED\${ACTIVESEED}_} >> \${FIRSTSEED/_SEED1/}
      else
         tail -n +2 \${FIRSTSEED/_SEED1_/_SEED\${ACTIVESEED}_} >> \${FIRSTSEED/_SEED1/}
      fi
      ACTIVESEED=\$((ACTIVESEED + 1))
    done
  fi
done

echo "Renaming raw stats"
for TYPE in _ _tfce_ ; do
  for FIRSTSEED in \$(imglob -extension "${ROOTNAME}_SEED1\${TYPE}tstat"* "${ROOTNAME}_SEED1\${TYPE}fstat"*) ; do
    if [ -e \$FIRSTSEED ] ; then
      cp \$FIRSTSEED \${FIRSTSEED/_SEED1/}
    fi
  done
done

ACTIVESEED=1
while [ \$ACTIVESEED -le $SLOTS_PER_CONTRAST ] ; do
  rm -rf "${ROOTNAME}_SEED\${ACTIVESEED}"*_p_*
  rm -rf "${ROOTNAME}_SEED\${ACTIVESEED}"*_corrp_*
  rm -rf \$(imglob -extensions "${ROOTNAME}_SEED\${ACTIVESEED}_"?stat*)
  rm -rf "${ROOTNAME}_SEED\${ACTIVESEED}_"*perm_*.txt "${ROOTNAME}_SEED\${ACTIVESEED}_"*_p_*.txt "${ROOTNAME}_SEED\${ACTIVESEED}_"*_corrp_*.txt

  ACTIVESEED=\$((ACTIVESEED + 1))
done

echo "Done"
combineScript
) > "${DIRNAME}/${BASENAME}.defragment"
chmod +x "${DIRNAME}/${BASENAME}.defragment"

DEFRAGMENT_TIME=20
if [ ${REQUESTED_SLOTS} -ge 150 ] ; then
  DEFRAGMENT_TIME=40
fi

fsl_sub -j $GENERATE_ID -T ${DEFRAGMENT_TIME} -l "${DIRNAME}/${BASENAME}_logs/" -N "${BASENAME}.defragment" "${DIRNAME}/${BASENAME}.defragment"
